### ISSUE TITLE
Where to find film emulation filters?

### ISSUE THREAD

**Issue by mainrs** [GreycLab/gmic-community#277]
I stumbled across this blog post about film emulation: https://patdavid.net/2013/09/film-emulation-presets-in-gmic-gimp/

It mentions that this project has them builtin. However, I could not find the filters within the repository. Where exactly are they?

**Comment by dtschump** [comment]
They are available in filter **Colors / Simulate Film**

![image](https://github.com/GreycLab/gmic-community/assets/10114565/70d06753-3776-4692-a55a-a572944d5494)

**Comment by mainrs** [comment]
Thanks for the answer. I was looking into how these are actually implemented. The blog post I mentioned writes about color LOT, but I couldn't find them in the repository. Can you help me out?

**Comment by dtschump** [comment]
In that case, the implementation is located in the G'MIC stdlib : https://raw.githubusercontent.com/GreycLab/gmic/master/src/gmic_stdlib.gmic
(filter 'Simulate Film`, line 45798).

This filter is based on the use of the `decompress_clut` command (defined at line 11139), and `map_clut` (defined at line 12907). All the Color LUTs are stored in file `gmic_cluts.gmz` (https://github.com/GreycLab/gmic/blob/master/resources/gmic_cluts.gmz), in a compressed form. The compression algorithm used is described in this research paper : [Reconstruction of Smooth 3D Color Functions from Keypoints: Application to Lossy Compression and Exemplar-Based Generation of Color LUTs.](https://tschumperle.users.greyc.fr/publications/tschumperle_siims20.pdf)

All this together makes actually a quite complex filter to understand.

**Comment by mainrs** [comment]
Thank you for the detailed explanations! Before putting effort into something that already exists:

Is there a CLI tool that allows be to unpack the `gmic_cluts.gmz` archive file?

**Comment by mainrs** [comment]
Thank you!
